
import { Icon } from "icon.slint";

IconText := Rectangle {
	property <[image]> icons;	 
	property <string> input;
	property <percent> scale;
	property <int> font-weight;
	property <string> font-family;
	property <brush> element-color;
	scale: 100%;

	height: 15px;
	
	Icon { 
        icon-sources: icons;
        y: parent.height / 2 - height / 2;
		element-color: parent.element-color;
		// colorize: #C44748;
		scale: parent.scale;
	}

	Text { 
		x: 20px * parent.scale + 10px;
        y: parent.height / 2 - height / 2;
		text: input;
		font-size: 20px * parent.scale;
		font-weight: parent.font-weight;
		font-family: parent.font-family;
	}
}
